// ── DATA ──────────────────────────────────────────────────────────────
function _defaultDrills() {
  return [
    { id:1,  dur:30, name:'Wall Ball Testing',        notes:'Partners — 2 groups' },
    { id:2,  dur:10, name:'Warm Up',                  notes:'Sticks to the Outside' },
    { id:3,  dur:10, name:'Meatloaf',                 notes:'3 Stations: GB Trail, 2v1 GB, Gauntlet' },
    { id:4,  dur:10, name:'GB Fundies',               notes:'O: Fundy Shooting (Turn & Shoot, Swat Fly) · D: Hern' },
    { id:5,  dur:12, name:'O/D Split',                notes:'O & D split sessions' },
    { id:6,  dur:15, name:'3v3 Corner GBs to Goal',   notes:'Competitive — switch sides halfway through' },
    { id:7,  dur:10, name:'2v2 +1 Circle GBs',        notes:'Competitive' },
    { id:8,  dur:10, name:'1v1 Diamond',              notes:'Ohio to pairs' },
    { id:9,  dur:10, name:'2v2',                      notes:'From Sides' },
    { id:10, dur:15, name:'Numbers Drill',            notes:'' },
    { id:11, dur:15, name:'Buildup Conditioning',     notes:'Quarter, Half, Full, Half, Quarter' },
  ];
}

let days = [
  { drills: _defaultDrills(), nextId: 100, dragSrcDrill: null, startAmPm: 'AM' },
  { drills: [],               nextId: 200, dragSrcDrill: null, startAmPm: 'AM' },
  { drills: [],               nextId: 300, dragSrcDrill: null, startAmPm: 'AM' },
];

// Drill library (master list, organized by category)
let drillLibrary = [
  // Groundballs
  { lid:1,   name:'1v1v1',                               dur:10, type:'Groundballs' },
  { lid:2,   name:'4v4 corner',                          dur:10, type:'Groundballs' },
  { lid:3,   name:'Apache',                              dur:10, type:'Groundballs' },
  { lid:4,   name:'4v3 Box GBs',                         dur:10, type:'Groundballs' },
  { lid:5,   name:'MF GBs - Tight Space in Box',         dur:10, type:'Groundballs' },
  { lid:6,   name:'Jailbreak GBs',                       dur:10, type:'Groundballs' },
  { lid:7,   name:'Gauntlet GBs',                        dur:10, type:'Groundballs' },
  { lid:8,   name:'GB w/ Trail',                         dur:10, type:'Groundballs' },
  { lid:9,   name:'Butt to Butt GBs',                    dur:10, type:'Groundballs' },
  { lid:10,  name:'Hockey/Soccer Lacrosse GBs',          dur:10, type:'Groundballs' },
  { lid:11,  name:'Circle GBs',                          dur:10, type:'Groundballs' },
  // Transition/Odd Numbers
  { lid:12,  name:'Numbers',                             dur:10, type:'Transition/Odd Numbers' },
  { lid:13,  name:'2v1 From Wing for 4v3 or 5v4',        dur:10, type:'Transition/Odd Numbers' },
  { lid:14,  name:'West Genny',                          dur:10, type:'Transition/Odd Numbers' },
  { lid:15,  name:'4v3 progress to 6v6',                 dur:12, type:'Transition/Odd Numbers' },
  { lid:16,  name:'Classic 4v3/Slow Breaks',             dur:10, type:'Transition/Odd Numbers' },
  { lid:17,  name:'Box Build Up/ ball start w/ goal',    dur:10, type:'Transition/Odd Numbers' },
  { lid:18,  name:'3v2 Sides',                           dur:10, type:'Transition/Odd Numbers' },
  { lid:19,  name:'3v2 ark',                             dur:10, type:'Transition/Odd Numbers' },
  { lid:20,  name:'Tennis Ball Drills',                  dur:10, type:'Transition/Odd Numbers' },
  { lid:21,  name:'4x3 box w/ forced actions',           dur:10, type:'Transition/Odd Numbers' },
  // Stickwork
  { lid:22,  name:'Partner Passing',                     dur:10, type:'Stickwork' },
  { lid:23,  name:'Line Drills',                         dur:10, type:'Stickwork' },
  { lid:24,  name:'Meatloaf',                            dur:10, type:'Stickwork' },
  { lid:25,  name:'Diamond Hardball',                    dur:10, type:'Stickwork' },
  { lid:26,  name:'Star Passing',                        dur:10, type:'Stickwork' },
  { lid:27,  name:'Spoke Passing',                       dur:10, type:'Stickwork' },
  { lid:28,  name:'3 Man Passing',                       dur:10, type:'Stickwork' },
  { lid:29,  name:'3 Man Weave',                         dur:10, type:'Stickwork' },
  { lid:30,  name:'Full FIeld Passing',                  dur:10, type:'Stickwork' },
  { lid:31,  name:'Keepaway 4v3 Box O/D',                dur:10, type:'Stickwork' },
  { lid:32,  name:'Double Keepaway',                     dur:10, type:'Stickwork' },
  { lid:33,  name:'Pressure Passing',                    dur:10, type:'Stickwork' },
  // O Skills
  { lid:34,  name:'Turn and Shoot',                      dur:10, type:'O Skills' },
  { lid:35,  name:'Swat the FLy',                        dur:10, type:'O Skills' },
  { lid:36,  name:'Over the Top Shooting',               dur:10, type:'O Skills' },
  { lid:37,  name:'Across the Top Shooting',             dur:10, type:'O Skills' },
  { lid:38,  name:'Roll Backs',                          dur:10, type:'O Skills' },
  { lid:39,  name:'Spoke',                               dur:10, type:'O Skills' },
  { lid:40,  name:'Bucket Drill',                        dur:10, type:'O Skills' },
  { lid:41,  name:'Redodge Drill',                       dur:10, type:'O Skills' },
  { lid:42,  name:'Coming Off PIck Shots',               dur:10, type:'O Skills' },
  { lid:43,  name:'Island X',                            dur:10, type:'O Skills' },
  { lid:44,  name:'Back to Back Stepdowns',              dur:10, type:'O Skills' },
  { lid:45,  name:'Cut the Corners Shooting',            dur:10, type:'O Skills' },
  { lid:46,  name:'Under/Hitch Shooting',                dur:10, type:'O Skills' },
  { lid:47,  name:'Over/Around Extra Net Shooting',      dur:10, type:'O Skills' },
  { lid:48,  name:'3 Cone Dodging',                      dur:10, type:'O Skills' },
  { lid:49,  name:'3x Small Nets',                       dur:10, type:'O Skills' },
  // D Skills
  { lid:50,  name:'Trailing Alley/Slide',                dur:10, type:'D Skills' },
  { lid:51,  name:'Ride The Rail',                       dur:10, type:'D Skills' },
  { lid:52,  name:'Hockey',                              dur:10, type:'D Skills' },
  { lid:53,  name:'Knee Down Drill',                     dur:10, type:'D Skills' },
  { lid:54,  name:'Rabbit Drill',                        dur:10, type:'D Skills' },
  { lid:55,  name:'Bethesda Drill (Vike Ride)',          dur:10, type:'D Skills' },
  { lid:56,  name:'3 Vertex Line',                       dur:10, type:'D Skills' },
  { lid:57,  name:'Approach Drill',                      dur:10, type:'D Skills' },
  { lid:58,  name:'Stange Passing',                      dur:10, type:'D Skills' },
  { lid:59,  name:'Shovel GBs',                          dur:10, type:'D Skills' },
  { lid:60,  name:'Overs',                               dur:10, type:'D Skills' },
  { lid:61,  name:'Coma Drill',                          dur:10, type:'D Skills' },
  // Man to Man
  { lid:62,  name:'Diamond 1v1',                         dur:10, type:'Man to Man' },
  { lid:63,  name:'Build Up 1,2,3,4',                    dur:10, type:'Man to Man' },
  { lid:64,  name:'1v1v1 from X',                        dur:10, type:'Man to Man' },
  { lid:65,  name:'2v2 Wings',                           dur:10, type:'Man to Man' },
  { lid:66,  name:'4v4 with Coach Outlets',              dur:10, type:'Man to Man' },
  { lid:67,  name:'1v1 w/ Slide',                        dur:10, type:'Man to Man' },
  { lid:68,  name:'In Tight 1v1',                        dur:10, type:'Man to Man' },
  { lid:69,  name:'Defense Pressure - 4 on Outside',     dur:10, type:'Man to Man' },
  { lid:70,  name:'Y Drill - Transfer at X',             dur:10, type:'Man to Man' },
  { lid:71,  name:'4v4 Plus One at X',                   dur:10, type:'Man to Man' },
  // Ride/Clear
  { lid:72,  name:'Breakouts',                           dur:10, type:'Ride/Clear' },
  { lid:73,  name:'Vike Ride Alley Drill',               dur:10, type:'Ride/Clear' },
  { lid:74,  name:'Field Reversal Vike Ride',            dur:10, type:'Ride/Clear' },
  { lid:75,  name:'Bethesda Drill',                      dur:10, type:'Ride/Clear' },
  { lid:76,  name:'Turn Em Drill with Approach/Quick Over', dur:10, type:'Ride/Clear' },
  // Goalie
  { lid:77,  name:'Footie and Corners',                  dur:10, type:'Goalie' },
  { lid:78,  name:'Whack-a-Mole',                        dur:10, type:'Goalie' },
  { lid:79,  name:'Juggling',                            dur:10, type:'Goalie' },
  { lid:80,  name:'Hand Slap',                           dur:10, type:'Goalie' },
  { lid:81,  name:'Egg Toss',                            dur:10, type:'Goalie' },
  { lid:82,  name:'5-Point Arc',                         dur:10, type:'Goalie' },
  { lid:83,  name:'10-Point Arc',                        dur:10, type:'Goalie' },
  { lid:84,  name:'Turn and Save',                       dur:10, type:'Goalie' },
  { lid:85,  name:'Top Hand Only',                       dur:10, type:'Goalie' },
  { lid:86,  name:'Bottom Hand Only',                    dur:10, type:'Goalie' },
  { lid:87,  name:'UVA Drill',                           dur:10, type:'Goalie' },
  { lid:88,  name:'Bad Andy',                            dur:10, type:'Goalie' },
  { lid:89,  name:'Shuffle Shuffle Save',                dur:10, type:'Goalie' },
  { lid:90,  name:'Offside Hip from Knees',              dur:10, type:'Goalie' },
  { lid:91,  name:'Butt End',                            dur:10, type:'Goalie' },
  { lid:92,  name:'Cone Swat',                           dur:10, type:'Goalie' },
  { lid:93,  name:'Cone Catch',                          dur:10, type:'Goalie' },
  { lid:94,  name:'Tennis Racket',                       dur:10, type:'Goalie' },
  { lid:95,  name:'Lateral Cone Cover',                  dur:10, type:'Goalie' },
  { lid:96,  name:'Lateral Cone Digs',                   dur:10, type:'Goalie' },
  { lid:97,  name:'Explosive Footwork',                  dur:10, type:'Goalie' },
  { lid:98,  name:'Walk the Line',                       dur:10, type:'Goalie' },
  // Faceoff
  { lid:99,  name:'One-Hand Build Up R/L',               dur:10, type:'Faceoff' },
  { lid:100, name:'Three Whistle Drill',                 dur:10, type:'Faceoff' },
  { lid:101, name:'3 Exits / 4 Zones',                   dur:10, type:'Faceoff' },
  { lid:102, name:'Gorillla Walk',                       dur:10, type:'Faceoff' },
  { lid:103, name:'Rock Paper Scissors',                 dur:10, type:'Faceoff' },
  { lid:104, name:'Hand slap',                           dur:10, type:'Faceoff' },
];

let depthData = {
  'ATTACK':        { cls:'att', players:['Tommy G','Danny','Colten','Jordan','Buck','Angus?','Byrd/Lowe?'] },
  'MIDFIELD':      { cls:'mid', players:['Sean','Arkin','Dylan?','Jude','Bo?','Ziggy Powell','Magnus','Zach Worthen'] },
  'DEFENSE — CD':  { cls:'def', players:['Durke','Lukas','Charm','Elliot','Henry','Cooper'] },
  'DEFENSE — DM':  { cls:'def', players:['Franny','Conor G','Georges','Rafe?','Zaki?'] },
  'DEFENSE — LSM': { cls:'def', players:['T-Sull','Jack Cummings','Aden (SSDM?)'] },
  'GOALIE':        { cls:'gol', players:['Beckett'] },
  'FACE-OFF':      { cls:'fo',  players:['Knox','Jake'] },
  'INJURED':       { cls:'inj', players:['Danny (ankle)','Cooper (mono)'] },
};

let nextLid = 200;
let dragSrcPlayer = null;
let libOpen = false;
let libForDay = 0;
